# Generated by Django 4.0.5 on 2022-07-13 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parks', '0002_alter_autoparksmodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoparksmodel',
            options={'ordering': ('id',)},
        ),
    ]
