# Generated by Django 4.0.5 on 2022-07-16 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auto_parks', '0003_alter_autoparksmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoparksmodel',
            name='owners',
            field=models.ManyToManyField(related_name='auto_parks', to=settings.AUTH_USER_MODEL),
        ),
    ]
