# Generated by Django 4.0.5 on 2022-07-06 13:41

from django.db import migrations, models

import apps.users.services


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profilemodel_age_alter_profilemodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=apps.users.services.upload_to),
        ),
    ]
