# Generated by Django 4.0.5 on 2022-06-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('monitor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'computers',
            },
        ),
    ]
